### ISSUE TITLE
6. Создание и настройка базы данных

### ISSUE THREAD

**Issue by Roubeq** [NaysasEnterprise/NSS#29]
1. Спроектировать базу данных для хранения данных о клиентах, заказах и пунктах выдачи заказов (ПВЗ).
2. Подготовить SQL-скрипты для создания таблиц: clients, orders, pickup_points.
3. Настроить связи между таблицами (например, каждый заказ связан с клиентом и с ПВЗ).

В файлике с бд отдельным.

**Comment by Rina199999** [comment]
Взяла задачу
