### ISSUE TITLE
7. Разработка серверной части (настройка сокета и обработка запросов)

### ISSUE THREAD

**Issue by Roubeq** [NaysasEnterprise/NSS#30]
ДЛЯ СТОРОНЫ КЛИЕНТА
1. Для начала сделать 2 версии кода(клиент и сервер).
2. Настроить серверное приложение для обработки клиентских запросов через сокеты.
3. Обеспечить обработку базовых операций: вход, регистрация, добавление заказа и поиск заказа.
Задачи: (как подробное описание)
Настроить прослушивание порта и подключение клиентов.
Реализовать маршрутизацию запросов (например, регистрация, вход, добавление заказа, проверка статуса заказа).
Подготовить функции, чтобы связывать запросы клиента с операциями базы данных через интерфейс, разработанный человеком, который возьмет 6-ую задачку.
Протестировать серверные функции и подготовить примеры запросов.

**Comment by Rina199999** [comment]
Взяла задачу
