### ISSUE TITLE
8. Модуль авторизации и регистрации клиентов

### ISSUE THREAD

**Issue by Roubeq** [NaysasEnterprise/NSS#31]
1. Создать функции для регистрации нового клиента и входа в систему.
2. Проверить существование клиента и присвоение ID через базу данных.
Задачи:
Разработать функции регистрации, входа, и проверки существования клиента.
Настроить проверку данных (например, уникальность имени, корректность ID).
Связать с сервером, чтобы можно было вызвать регистрацию и вход через запросы клиента.
Подготовить тестовые случаи и документацию по использованию.

**Comment by KoRT1N** [comment]
Взял задачу
