### ISSUE TITLE
10. Создание и управление ПВЗ

### ISSUE THREAD

**Issue by Roubeq** [NaysasEnterprise/NSS#33]
1. Реализовать функции для добавления нового ПВЗ и отображения всех ПВЗ.
2. Связать с сервером для создания и хранения ПВЗ в базе данных.

Задачи:
Написать функции для добавления ПВЗ, генерации ID и сохранения информации в базе данных.
Разработать функции для отображения списка всех ПВЗ.
Настроить связь с сервером, чтобы администратор мог управлять ПВЗ через интерфейс.
Протестировать добавление и вывод ПВЗ, документировать API для работы с ПВЗ.

**Comment by teslasteria31** [comment]
Closed
