### ISSUE TITLE
15. Пользователи и заказы

### ISSUE THREAD

**Issue by Roubeq** [NaysasEnterprise/NSS#50]
1. Сделать функцию, которая реализует оформление заказа клиентом. (сделать можно у класса OPP, чтобы потом добавление заказа мы всунули и в клиента, и в админа, т.е чтоб у админа была возможность заказ сделать клиенту(допустим придет бабушка и скажет мне надо заказатть это и это..) )
2. Реализовать функцию для отмены заказа.
3. Оформить функцию, которая бы выводила всю информацию о заказе.
4. Поиск заказа

**Comment by AnastasiaNezh** [comment]
Для 1-ого пунка сделала еще функцию отображения всех заказов, т.к чтобы что то заказать, нужно сначала увидеть что можно заказать

**Comment by AnastasiaNezh** [comment]
Добавила возможность заказывать товары (пока не особо так как нужно, но работает) и также отображение всех заказов

**Comment by AnastasiaNezh** [comment]
добавила возможность отмены заказов

**Comment by AnastasiaNezh** [comment]
поправила ошибки с добавлением заказа и отображением в функции получения всех заказов

**Comment by AnastasiaNezh** [comment]
а каким образом мы будем менять заказ?

**Comment by Roubeq** [comment]
изменять заказ да, что то я не подумал, уберем эту фигню)

**Comment by AnastasiaNezh** [comment]
сделала функцию поиска заказов
